/**
 * An AI-voiced outbound call needs prior express WRITTEN consent.
 *
 * Law relied on (cited, not paraphrased into new obligations):
 *   - 47 U.S.C. § 227(b)(1)(A)/(B): no call using "an artificial or prerecorded
 *     voice" to a cell phone, or to a residential line, without the called
 *     party's prior express consent.
 *   - 47 C.F.R. § 64.1200(a)(2)-(3) and (f)(9): for a call that introduces an
 *     advertisement or is telemarketing, that consent must be "prior express
 *     written consent" — a written agreement, signed (E-SIGN suffices), that
 *     clearly authorizes the seller to deliver such calls using an artificial
 *     or prerecorded voice to the number given, and is not a condition of
 *     purchase.
 *   - FCC Declaratory Ruling, CG Docket No. 23-362, FCC 24-17 (Feb. 8, 2024):
 *     voices generated by artificial intelligence are "artificial" voices
 *     under the TCPA.
 *
 * AcreOS places no AI-voiced outbound call today. This is the gate that makes
 * one impossible to ship without consent: every outbound call goes through
 * CommsRouter.initiateCall, every call must declare its voice, and an
 * "artificial" voice is refused unless the org holds a written consent
 * record for that number that names artificial / prerecorded / AI voice
 * calls, with no revocation after it. Any read failure refuses (fail closed).
 */
import { and, desc, eq, inArray } from "drizzle-orm";
import { leadConsentEvents, leads } from "@shared/schema";

/** What a call says about who is speaking. Required on every call. */
export type CallVoice = { kind: "human" } | { kind: "artificial" };

export class AiVoiceConsentRequiredError extends Error {
  readonly code = "AI_VOICE_CONSENT_REQUIRED" as const;
  constructor(readonly to: string, readonly why: string) {
    super(`AI-voiced call to ${to} refused: ${why}. An artificial (including AI-generated) voice call needs the called party's prior express written consent (47 U.S.C. § 227(b); 47 C.F.R. § 64.1200(a)(2), (f)(9); FCC 24-17).`);
    this.name = "AiVoiceConsentRequiredError";
  }
}

/** The consent language must name the thing consented to. */
export const ARTIFICIAL_VOICE_CONSENT_TEXT = /\b(?:artificial|prerecorded|pre-recorded|automated|AI[- ]generated|synthetic|computer[- ]generated)\b[\s\S]{0,40}\bvoice|\bvoice\b[\s\S]{0,40}\b(?:artificial|prerecorded|pre-recorded|AI[- ]generated|synthetic)\b/i;

export function digitsOf(phone: string): string {
  const d = phone.replace(/[^0-9]/g, "");
  return d.length === 11 && d.startsWith("1") ? d.slice(1) : d;
}

export interface ConsentEventRow {
  eventType: string;
  channels: string[] | null;
  source: string;
  consentText: string | null;
  metadata: unknown;
  createdAt: Date;
}

/**
 * Pure: does this history (newest first) hold live written consent to
 * artificial-voice calls? The newest phone-channel event decides: a revocation
 * after the grant ends it.
 */
export function hasWrittenArtificialVoiceConsent(events: ConsentEventRow[]): { ok: true } | { ok: false; why: string } {
  const phone = events.filter((e) => Array.isArray(e.channels) && e.channels.includes("phone"));
  if (phone.length === 0) return { ok: false, why: "no phone consent on record for this number" };
  const latest = phone[0];
  if (latest.eventType !== "granted") return { ok: false, why: `the latest phone consent event is "${latest.eventType}"` };
  if (latest.source !== "written") return { ok: false, why: `consent was captured as "${latest.source}", not in writing` };
  const meta = (latest.metadata ?? {}) as { artificialVoice?: unknown };
  const named = meta.artificialVoice === true || ARTIFICIAL_VOICE_CONSENT_TEXT.test(latest.consentText ?? "");
  if (!named) return { ok: false, why: "the written consent does not authorize artificial or prerecorded voice calls" };
  return { ok: true };
}

/** The call-placing gate. Throws AiVoiceConsentRequiredError unless allowed. */
export async function assertCallVoiceAllowed(opts: { voice: CallVoice | undefined; to: string; organizationId?: number }): Promise<void> {
  if (!opts.voice || (opts.voice.kind !== "human" && opts.voice.kind !== "artificial")) {
    throw new AiVoiceConsentRequiredError(opts.to, "the call did not declare whether its voice is human or artificial");
  }
  if (opts.voice.kind === "human") return;
  if (opts.organizationId == null) throw new AiVoiceConsentRequiredError(opts.to, "no organization owns the consent record");
  const digits = digitsOf(opts.to);
  if (digits.length < 10) throw new AiVoiceConsentRequiredError(opts.to, "the number is not a callable phone number");
  let events: ConsentEventRow[];
  try {
    const { db } = await import("../../db");
    const matches = await db
      .select({ id: leads.id })
      .from(leads)
      .where(and(eq(leads.organizationId, opts.organizationId), inArray(leads.phoneNormalized, [digits, `1${digits}`])));
    if (matches.length === 0) throw new AiVoiceConsentRequiredError(opts.to, "the number belongs to no lead in this organization");
    events = (await db
      .select({
        eventType: leadConsentEvents.eventType,
        channels: leadConsentEvents.channels,
        source: leadConsentEvents.source,
        consentText: leadConsentEvents.consentText,
        metadata: leadConsentEvents.metadata,
        createdAt: leadConsentEvents.createdAt,
      })
      .from(leadConsentEvents)
      .where(and(eq(leadConsentEvents.organizationId, opts.organizationId), inArray(leadConsentEvents.leadId, matches.map((m) => m.id))))
      .orderBy(desc(leadConsentEvents.createdAt), desc(leadConsentEvents.id))) as ConsentEventRow[];
  } catch (err) {
    if (err instanceof AiVoiceConsentRequiredError) throw err;
    throw new AiVoiceConsentRequiredError(opts.to, `the consent record could not be read (${err instanceof Error ? err.message : String(err)})`);
  }
  const verdict = hasWrittenArtificialVoiceConsent(events);
  if (!verdict.ok) throw new AiVoiceConsentRequiredError(opts.to, verdict.why);
}
