import type { PlaybookTemplate } from "@shared/schema";

export const PLAYBOOK_TEMPLATES: PlaybookTemplate[] = [
  {
    id: "acquisition_sprint",
    name: "Acquisition Sprint",
    description: "A complete workflow to find, research, and make an offer on a land parcel in 7 days or less.",
    category: "acquisition",
    estimatedDuration: "7 days",
    steps: [
      {
        id: "identify_target_county",
        title: "Identify Target County",
        description: "Research and select a county with favorable market conditions for land investing. Look for low competition, reasonable prices, and good resale potential.",
        actionType: "navigate",
        actionLabel: "Browse Counties",
        actionUrl: "/counties",
        icon: "MapPin",
        estimatedMinutes: 60,
      },
      {
        id: "pull_tax_delinquent_list",
        title: "Pull Tax Delinquent List",
        description: "Download or import the tax delinquent property list from your target county. These owners are motivated sellers.",
        actionType: "navigate",
        actionLabel: "Import Leads",
        actionUrl: "/leads",
        icon: "FileSpreadsheet",
        estimatedMinutes: 30,
      },
      {
        id: "skip_trace_leads",
        title: "Skip Trace Leads",
        description: "Run skip tracing on your imported leads to get current contact information including phone numbers and mailing addresses.",
        actionType: "navigate",
        actionLabel: "Skip Trace",
        actionUrl: "/leads",
        icon: "Search",
        estimatedMinutes: 15,
      },
      {
        id: "send_mail_campaign",
        title: "Send Mail Campaign",
        description: "Create and send your direct mail campaign to the leads. Use proven letter templates that convert.",
        actionType: "navigate",
        actionLabel: "Create Campaign",
        actionUrl: "/campaigns",
        icon: "Mail",
        estimatedMinutes: 45,
      },
      {
        id: "track_responses",
        title: "Track Responses",
        description: "Monitor incoming calls, texts, and mail responses. Log all communication in the lead record.",
        actionType: "navigate",
        actionLabel: "View Inbox",
        actionUrl: "/inbox",
        icon: "MessageSquare",
        estimatedMinutes: 20,
      },
      {
        id: "research_property",
        title: "Research Property",
        description: "When you get a positive response, research the property thoroughly: verify ownership, check for liens, review GIS data.",
        actionType: "navigate",
        actionLabel: "Property Research",
        actionUrl: "/properties",
        icon: "FileSearch",
        estimatedMinutes: 60,
      },
      {
        id: "generate_offer",
        title: "Generate Offer",
        description: "Use AI to generate a competitive offer based on market comps and your target profit margin.",
        actionType: "navigate",
        actionLabel: "Create Offer",
        actionUrl: "/offers",
        icon: "DollarSign",
        estimatedMinutes: 15,
      },
      {
        id: "create_deal",
        title: "Create Deal",
        description: "Convert the accepted offer into a deal and begin the closing process.",
        actionType: "create_deal",
        actionLabel: "Create Deal",
        actionUrl: "/deals",
        icon: "Handshake",
        estimatedMinutes: 10,
      },
    ],
  },
  {
    id: "due_diligence",
    name: "Due Diligence Checklist",
    description: "Comprehensive checklist to verify property ownership, check for issues, and ensure a clean transaction.",
    category: "due_diligence",
    estimatedDuration: "3-5 days",
    steps: [
      {
        id: "verify_ownership",
        title: "Verify Ownership",
        description: "Confirm the seller is the actual owner by checking county assessor records and deed history.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "UserCheck",
        estimatedMinutes: 30,
      },
      {
        id: "title_search",
        title: "Title Search",
        description: "Run a title search to check for liens, encumbrances, judgments, and other title issues.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "FileText",
        estimatedMinutes: 60,
      },
      {
        id: "check_back_taxes",
        title: "Check Back Taxes",
        description: "Verify the amount of back taxes owed and factor this into your offer calculations.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "Receipt",
        estimatedMinutes: 20,
      },
      {
        id: "survey_review",
        title: "Survey Review",
        description: "Review existing survey or order a new one. Confirm boundaries, easements, and legal description.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "Ruler",
        estimatedMinutes: 45,
      },
      {
        id: "environmental_check",
        title: "Environmental Check",
        description: "Check for wetlands, flood zones, endangered species habitats, and contamination risks.",
        actionType: "navigate",
        actionLabel: "View GIS Data",
        actionUrl: "/properties",
        icon: "Leaf",
        estimatedMinutes: 30,
      },
      {
        id: "zoning_verification",
        title: "Zoning Verification",
        description: "Verify current zoning and confirm what uses are permitted on the property.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "Building",
        estimatedMinutes: 20,
      },
      {
        id: "access_verification",
        title: "Verify Legal Access",
        description: "Confirm the property has legal road access or an easement for ingress/egress.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "Route",
        estimatedMinutes: 30,
      },
      {
        id: "utilities_check",
        title: "Utilities Check",
        description: "Determine availability of power, water, sewer, and internet connectivity.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "Plug",
        estimatedMinutes: 30,
      },
    ],
  },
  {
    id: "disposition_launch",
    name: "Disposition Launch",
    description: "Step-by-step process to list, market, and close on your land sale.",
    category: "disposition",
    estimatedDuration: "30-90 days",
    steps: [
      {
        id: "prepare_listing",
        title: "Prepare Listing",
        description: "Create compelling listing content with professional photos, descriptions, and key property features.",
        actionType: "navigate",
        actionLabel: "Create Listing",
        actionUrl: "/listings",
        icon: "Image",
        estimatedMinutes: 60,
      },
      {
        id: "set_pricing",
        title: "Set Pricing Strategy",
        description: "Analyze comparable sales and set your asking price and owner financing terms.",
        actionType: "navigate",
        actionLabel: "Price Analysis",
        actionUrl: "/properties",
        icon: "TrendingUp",
        estimatedMinutes: 30,
      },
      {
        id: "list_on_marketplaces",
        title: "List on Marketplaces",
        description: "Post your listing to Facebook Marketplace, Craigslist, LandWatch, and other platforms.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "Share2",
        estimatedMinutes: 45,
      },
      {
        id: "contact_buyer_list",
        title: "Contact Buyer List",
        description: "Reach out to your existing buyer list with the new property opportunity.",
        actionType: "navigate",
        actionLabel: "Send Campaign",
        actionUrl: "/campaigns",
        icon: "Users",
        estimatedMinutes: 20,
      },
      {
        id: "handle_inquiries",
        title: "Handle Inquiries",
        description: "Respond to buyer inquiries, answer questions, and schedule property viewings if needed.",
        actionType: "navigate",
        actionLabel: "View Inbox",
        actionUrl: "/inbox",
        icon: "MessageCircle",
        estimatedMinutes: 30,
      },
      {
        id: "qualify_buyers",
        title: "Qualify Buyers",
        description: "Pre-qualify interested buyers for financing and verify their ability to close.",
        actionType: "manual",
        actionLabel: "Mark Complete",
        icon: "ClipboardCheck",
        estimatedMinutes: 30,
      },
      {
        id: "negotiate_terms",
        title: "Negotiate Terms",
        description: "Negotiate final price and terms with your buyer. Use the deal calculator to model scenarios.",
        actionType: "navigate",
        actionLabel: "Deal Calculator",
        actionUrl: "/tools",
        icon: "Calculator",
        estimatedMinutes: 30,
      },
      {
        id: "generate_documents",
        title: "Generate Documents",
        description: "Create purchase agreement, promissory note, and deed using document templates.",
        actionType: "navigate",
        actionLabel: "Documents",
        actionUrl: "/documents",
        icon: "FileSignature",
        estimatedMinutes: 45,
      },
      {
        id: "close_deal",
        title: "Close the Deal",
        description: "Collect signatures, record the deed, and set up the note for payments if seller financing.",
        actionType: "create_deal",
        actionLabel: "Complete Sale",
        actionUrl: "/deals",
        icon: "CheckCircle2",
        estimatedMinutes: 60,
      },
    ],
  },
];

export function getPlaybookTemplate(templateId: string): PlaybookTemplate | undefined {
  return PLAYBOOK_TEMPLATES.find(t => t.id === templateId);
}

export function getPlaybooksByCategory(category: "acquisition" | "due_diligence" | "disposition"): PlaybookTemplate[] {
  return PLAYBOOK_TEMPLATES.filter(t => t.category === category);
}
