-- Phase 3 Week 14 (Sayuri-Vatanen §1): pgvector retrieval
--
-- Converts the `deal_patterns.embedding_vector` column from `jsonb` to
-- `vector(1536)` so we can:
--   • Use Postgres-native cosine distance (`<=>`) instead of pulling
--     every row to JS and computing cosine in process.
--   • Build an IVFFlat index for ANN search (sub-linear top-K lookups).
--
-- Dim choice: 1536 — matches OpenAI `text-embedding-3-small` (and the
-- legacy `text-embedding-ada-002`), which is the model wired into
-- `dealPatternCloning.generateEmbedding()`.
--
-- Conversion strategy: jsonb arrays serialize as `[0.1, 0.2, …]`, which
-- Postgres can cast to `vector` directly via `::vector`. Rows whose
-- jsonb payload is not the right shape (e.g. simple-embedding fallback
-- with 17 dims, or NULL) are nulled out and will be regenerated by the
-- embedding-refresh job.
--
-- Index: IVFFlat with `lists = 100` is the canonical starting point
-- per the pgvector README — appropriate for up to ~1M rows. CREATE
-- INDEX CONCURRENTLY because deal_patterns is a hot path.

-- 1) Sanitize jsonb payloads that aren't 1536-dim arrays. We coerce
--    any malformed embedding to NULL so the column-type ALTER below
--    doesn't trip on the cast.
UPDATE deal_patterns
SET embedding_vector = NULL
WHERE embedding_vector IS NOT NULL
  AND (
    jsonb_typeof(embedding_vector) <> 'array'
    OR jsonb_array_length(embedding_vector) <> 1536
  );

-- 2) Convert column type via USING expression.
ALTER TABLE deal_patterns
  ALTER COLUMN embedding_vector TYPE vector(1536)
  USING (
    CASE
      WHEN embedding_vector IS NULL THEN NULL
      ELSE embedding_vector::text::vector(1536)
    END
  );

-- 3) Track when each embedding was last computed so the rolling
--    7-day refresh job can prioritize stale rows.
ALTER TABLE deal_patterns
  ADD COLUMN IF NOT EXISTS embedding_refreshed_at timestamp;

UPDATE deal_patterns
SET embedding_refreshed_at = updated_at
WHERE embedding_vector IS NOT NULL
  AND embedding_refreshed_at IS NULL;

-- 4) IVFFlat ANN index for cosine similarity (`<=>`).
--    Build CONCURRENTLY so we don't block writes on a table that the
--    deal-pattern-cloning service writes into during normal operation.
CREATE INDEX CONCURRENTLY IF NOT EXISTS deal_patterns_embedding_ivfflat_idx
  ON deal_patterns
  USING ivfflat (embedding_vector vector_cosine_ops)
  WITH (lists = 100);

-- 5) Supporting btree index for the refresh job's "stale first" sweep.
CREATE INDEX IF NOT EXISTS deal_patterns_embedding_refreshed_at_idx
  ON deal_patterns (embedding_refreshed_at NULLS FIRST);
