-- Lens 16 Pillar K (Ursa / Note Servicer) — foundation tables.
--
-- A note servicer collects on notes owned by OTHERS (fund LPs, IRA holders,
-- family offices, trusts) and remits the proceeds, net of a servicing fee.
-- Distinct from `note_ownership_splits` (internal fractional ownership of
-- a note our org beneficially holds) — the rows below model the
-- third-party LEGAL OWNER OF RECORD that the servicing org reports to.
--
-- This migration is additive. No existing table is touched.

-- ─────────────────────────────────────────────────────────────────────────
-- note_ownership_of_record — who legally owns the cashflow.
--
-- Many notes have a single owner of record; some are fractionalised across
-- an LP, an IRA custodian, and a trust. We model history (effective_at /
-- superseded_at) so the servicer can answer "who owned this note on
-- 2026-04-15?" without losing prior periods' remittance records.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS note_ownership_of_record (
  id                varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id   integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  note_id           varchar NOT NULL REFERENCES acquired_notes(id) ON DELETE CASCADE,
  owner_org_id      integer NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  owner_type        text NOT NULL,
  basis_percentage  numeric(5,2) NOT NULL DEFAULT 100.00,
  effective_at      timestamptz NOT NULL DEFAULT now(),
  superseded_at     timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT note_owner_of_record_type_chk
    CHECK (owner_type IN ('org','lp','ira_custodian','trust')),
  CONSTRAINT note_owner_of_record_basis_chk
    CHECK (basis_percentage >= 0 AND basis_percentage <= 100)
);

CREATE INDEX IF NOT EXISTS note_owner_of_record_org_note_idx
  ON note_ownership_of_record(organization_id, note_id);
CREATE INDEX IF NOT EXISTS note_owner_of_record_owner_idx
  ON note_ownership_of_record(owner_org_id, superseded_at);
CREATE INDEX IF NOT EXISTS note_owner_of_record_active_idx
  ON note_ownership_of_record(organization_id, note_id)
  WHERE superseded_at IS NULL;

-- ─────────────────────────────────────────────────────────────────────────
-- servicer_remittances — per-owner monthly sub-ledger.
--
-- One row per (owner, period). Generated by the monthly remittance job
-- (server/services/servicerRemittance.ts) which sums note_payments for
-- every note where ownership_of_record points at owner_org_id, computes
-- the servicer fee (per-note % held on each ownership row — deferred —
-- or a flat org default), and writes a draft row. The PDF render is
-- queued separately so generation isn't blocked by render latency.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS servicer_remittances (
  id                varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id   integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  owner_org_id      integer NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  period_start      date NOT NULL,
  period_end        date NOT NULL,
  gross_cents       bigint NOT NULL DEFAULT 0,
  servicer_fee_cents bigint NOT NULL DEFAULT 0,
  net_cents         bigint NOT NULL DEFAULT 0,
  status            text NOT NULL DEFAULT 'draft',
  pdf_s3_key        text,
  generated_at      timestamptz NOT NULL DEFAULT now(),
  sent_at           timestamptz,
  paid_at           timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT servicer_remittance_status_chk
    CHECK (status IN ('draft','sent','paid')),
  CONSTRAINT servicer_remittance_period_chk
    CHECK (period_end >= period_start)
);

CREATE INDEX IF NOT EXISTS servicer_remit_org_owner_period_idx
  ON servicer_remittances(organization_id, owner_org_id, period_end DESC);
CREATE INDEX IF NOT EXISTS servicer_remit_org_status_idx
  ON servicer_remittances(organization_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS servicer_remit_uniq_period_uk
  ON servicer_remittances(organization_id, owner_org_id, period_start, period_end);

-- ─────────────────────────────────────────────────────────────────────────
-- servicer_licenses — per-state licensing posture.
--
-- Reg AB-style obligation hint: a servicer touching a regulated note in
-- state X must hold the right license (sub-servicer, master-servicer,
-- RMLO, etc.). This is a posture table — the actual filing is done by
-- counsel. The Servicer UI surfaces a coverage matrix + expiring-soon
-- highlights from this table.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS servicer_licenses (
  id              varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  state           text NOT NULL,
  license_type    text NOT NULL,
  license_number  text,
  expires_at      date,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT servicer_license_type_chk
    CHECK (license_type IN ('sub_servicer','master_servicer','rmlo','none_required'))
);

CREATE INDEX IF NOT EXISTS servicer_licenses_org_state_idx
  ON servicer_licenses(organization_id, state);
CREATE INDEX IF NOT EXISTS servicer_licenses_org_expiring_idx
  ON servicer_licenses(organization_id, expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS servicer_licenses_state_uk
  ON servicer_licenses(organization_id, state, license_type);
