/**
 * FounderTracesPage — agent action-replay.
 *
 * Every LLM call an agent makes writes a row to agent_llm_traces. This
 * page lists recent traces and lets the founder expand any row to see
 * the exact prompt + response — the canonical answer to "why did the
 * system do that?"
 *
 * Roadmap top-20 #8 (action-replay) + #10 (reasoning-trace viewer).
 */
import { useState, useId } from "react";
import { useQuery } from "@tanstack/react-query";
import { PageShell } from "@/components/page-shell";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/empty-state";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { FileCode, ChevronDown, ChevronRight, Clock } from "lucide-react";
import { relative, dollars } from "@/lib/format";
import { PageHeader } from "@/components/ui/page-header";
import { useDocumentTitle } from "@/hooks/use-document-title";

interface TraceSummary {
  id: number;
  agentCodename: string;
  purpose: string;
  decisionId: number | null;
  model: string;
  latencyMs: number | null;
  inputTokens: number | null;
  outputTokens: number | null;
  costCents: number | null;
  error: string | null;
  createdAt: string;
}

interface TraceDetail extends TraceSummary {
  organizationId: number | null;
  systemPrompt: string | null;
  userPrompt: string;
  response: string;
  metadata: Record<string, unknown>;
}

const AGENT_CHOICES = ["pax", "sophie_csm", "forge_revenue", "atlas_cto", "beacon_marketing", "ledger_finance"];

export function AgentTracesContent() {
  useDocumentTitle("Agent traces");
  const [agentFilter, setAgentFilter] = useState<string>("all");
  const filterId = useId();

  const { data, isLoading, isError, refetch } = useQuery<{ traces: TraceSummary[] }>({
    queryKey: [
      `/api/founder/intelligence/traces${agentFilter === "all" ? "" : `?agent=${agentFilter}`}`,
    ],
    staleTime: 30_000,
  });

  const traces = data?.traces ?? [];

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
        <PageHeader
          title="Agent traces"
          icon={<FileCode className="h-5 w-5 text-muted-foreground" aria-hidden="true" />}
          description="Every LLM call an agent makes lands here — the exact prompt sent, the exact response received, model, latency, token usage. Expand a row to see the full trace. This is the canonical answer to 'why did the system do that?'"
          actions={
            <div className="flex items-center gap-2">
              <Label htmlFor={filterId} className="sr-only">Filter by agent</Label>
              <Select value={agentFilter} onValueChange={setAgentFilter}>
                <SelectTrigger id={filterId} className="w-[180px]" data-testid="select-trace-agent" aria-label="Filter by agent">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All agents</SelectItem>
                  {AGENT_CHOICES.map((a) => (
                    <SelectItem key={a} value={a}>
                      {a}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          }
        />

        {isLoading ? (
          <Card>
            <CardContent className="p-6 space-y-3" role="status" aria-live="polite">
              <span className="sr-only">Loading agent traces…</span>
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
            </CardContent>
          </Card>
        ) : isError ? (
          <Card>
            <CardContent className="p-6 text-sm text-acr-neg" role="alert">
              Couldn't load traces. The trace log is unchanged —{" "}
              <button
                type="button"
                className="underline hover:no-underline"
                onClick={() => refetch()}
              >
                try again
              </button>.
            </CardContent>
          </Card>
        ) : traces.length === 0 ? (
          <EmptyState
            icon={FileCode}
            headline="No traces yet"
            subtitle={
              agentFilter === "all"
                ? "Agent LLM calls will start appearing here as they happen."
                : `No traces logged for ${agentFilter}. Try a different agent.`
            }
            // TODO(cta): traces are system-generated by LLM calls; no direct user action produces them
            cta={{ label: "", _noOp: true }}
          />
        ) : (
          <ul className="space-y-2" aria-label="Recent agent traces">
            {traces.map((t) => (
              <li key={t.id}>
                <TraceRow trace={t} />
              </li>
            ))}
          </ul>
        )}
    </div>
  );
}

export default function FounderTracesPage() {
  return (
    <PageShell label="Agent Traces">
      <AgentTracesContent />
    </PageShell>
  );
}

function TraceRow({ trace }: { trace: TraceSummary }) {
  const [expanded, setExpanded] = useState(false);
  const detailsId = useId();
  const { data: detailData, isLoading } = useQuery<{ trace: TraceDetail }>({
    queryKey: [`/api/founder/intelligence/traces/${trace.id}`],
    enabled: expanded,
    staleTime: 60 * 60_000, // traces are immutable
  });
  const detail = detailData?.trace;

  return (
    <Card>
      <CardContent className="p-3 space-y-2">
        <button
          type="button"
          className="w-full flex items-center gap-3 text-left flex-wrap"
          onClick={() => setExpanded((v) => !v)}
          aria-expanded={expanded}
          aria-controls={detailsId}
          aria-label={`${expanded ? "Collapse" : "Expand"} ${trace.agentCodename} trace: ${trace.purpose}`}
          data-testid={`trace-toggle-${trace.id}`}
        >
          {expanded ? (
            <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" aria-hidden="true" />
          ) : (
            <ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" aria-hidden="true" />
          )}
          <Badge variant="secondary" className="text-micro font-mono">
            {trace.agentCodename}
          </Badge>
          <span className="text-sm font-medium text-foreground">{trace.purpose}</span>
          <Badge variant="outline" className="text-micro">{trace.model}</Badge>
          {trace.error ? (
            <Badge variant="outline" className="text-micro border-acr-neg/30 text-acr-neg">
              Error
            </Badge>
          ) : null}
          <span className="ml-auto flex items-center gap-2 text-xs text-muted-foreground shrink-0">
            {trace.latencyMs != null && (
              <>
                <Clock className="h-3 w-3" aria-hidden="true" />
                <span className="tabular-nums">{trace.latencyMs}ms</span>
              </>
            )}
            {trace.costCents != null && <span className="tabular-nums">{dollars(trace.costCents)}</span>}
            <span className="tabular-nums">{relative(trace.createdAt)}</span>
          </span>
        </button>

        {expanded && (
          <div id={detailsId} className="pt-2 border-t space-y-3">
            {isLoading ? (
              <div role="status" aria-live="polite">
                <span className="sr-only">Loading trace details…</span>
                <Skeleton className="h-24 w-full" />
              </div>
            ) : detail ? (
              <>
                {detail.error && (
                  <div
                    role="alert"
                    className="rounded-md bg-acr-neg/5 border border-acr-neg/30 p-2 text-xs text-acr-neg dark:text-acr-neg font-mono whitespace-pre-wrap"
                  >
                    {detail.error}
                  </div>
                )}
                {detail.systemPrompt && (
                  <div>
                    <p className="text-micro uppercase tracking-wide text-muted-foreground mb-1">System prompt</p>
                    <pre className="rounded-md border bg-muted/30 text-[11px] font-mono leading-5 px-3 py-2 max-h-[240px] overflow-auto whitespace-pre-wrap">
                      {detail.systemPrompt}
                    </pre>
                  </div>
                )}
                <div>
                  <p className="text-micro uppercase tracking-wide text-muted-foreground mb-1">User prompt</p>
                  <pre className="rounded-md border bg-muted/30 text-[11px] font-mono leading-5 px-3 py-2 max-h-[240px] overflow-auto whitespace-pre-wrap">
                    {detail.userPrompt}
                  </pre>
                </div>
                <div>
                  <p className="text-micro uppercase tracking-wide text-muted-foreground mb-1">Response</p>
                  <pre className="rounded-md border bg-muted/30 text-[11px] font-mono leading-5 px-3 py-2 max-h-[360px] overflow-auto whitespace-pre-wrap">
                    {detail.response}
                  </pre>
                </div>
                {(detail.inputTokens != null || detail.outputTokens != null) && (
                  <dl className="flex gap-4 text-caption text-muted-foreground">
                    {detail.inputTokens != null && (
                      <div className="flex gap-1">
                        <dt>In:</dt>
                        <dd className="tabular-nums">{detail.inputTokens.toLocaleString()}</dd>
                      </div>
                    )}
                    {detail.outputTokens != null && (
                      <div className="flex gap-1">
                        <dt>Out:</dt>
                        <dd className="tabular-nums">{detail.outputTokens.toLocaleString()}</dd>
                      </div>
                    )}
                  </dl>
                )}
              </>
            ) : null}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
