// ============================================================================
// SHARED/SCHEMA/REG-Z.TS
// ----------------------------------------------------------------------------
// Reg-Z scaffolding for §1026.41 (periodic statements) and §1026.36(c)
// (prompt crediting, suspense bucket, late-fee non-pyramiding).
//
// Why a dedicated file: these tables form one cohesive regulatory boundary.
// A CFPB examiner asking "show me your §1026.41 implementation" should be
// able to read one file and see all four tables plus the field-by-field
// citation mapping in comments. Splitting across compliance.ts /
// notes-vertical.ts would have buried the regulatory intent.
//
// All amounts are integer cents (bigint). All citations are the C.F.R.
// section that authorises the field, written inline so a future Beatrice
// audit can trace each column to the rule that requires it.
// ============================================================================

import {
  pgTable,
  text,
  integer,
  bigint,
  boolean,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
  date,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { organizations } from "../schema";

// ============================================================================
// §1026.41 — PERIODIC STATEMENTS
// ----------------------------------------------------------------------------
// 12 C.F.R. §1026.41(b): a servicer must deliver a periodic statement for
// each billing cycle. (d) enumerates the required content. (e) governs
// exemptions (we do not currently rely on any). The row is generated by
// the monthly cron + manually re-runnable via the admin route; the PDF is
// rendered on demand from the row's persisted snapshot so the borrower
// can re-download exactly what we sent.
// ============================================================================

export const periodicStatements = pgTable(
  "periodic_statements",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: integer("organization_id")
      .references(() => organizations.id, { onDelete: "cascade" })
      .notNull(),
    // loanId is the originated `notes.id` (integer) cast to text so we can
    // hold either originated-note IDs or future loan types under one column
    // without a migration. The route resolves it back to the right table.
    loanId: text("loan_id").notNull(),
    loanType: text("loan_type").notNull().default("note"), // 'note' | 'acquired_note'

    // ── Cycle boundaries — §1026.41(b) ──────────────────────────────────
    cycleStart: date("cycle_start").notNull(),
    cycleEnd: date("cycle_end").notNull(),

    // ── Payment-due block — §1026.41(d)(1) ──────────────────────────────
    dueDate: date("due_date").notNull(),
    amountDueCents: bigint("amount_due_cents", { mode: "number" }).notNull(),
    // Breakdown of how the next payment will be applied. §1026.41(d)(1)(ii)
    // requires the explanation. Shape:
    //   { principal, interest, escrow, fees, optional_products }
    paymentApplicationExplanation: jsonb("payment_application_explanation")
      .$type<{
        principalCents: number;
        interestCents: number;
        escrowCents: number;
        feesCents: number;
      }>()
      .notNull(),

    // ── Account information — §1026.41(d)(3) ────────────────────────────
    principalBalanceCents: bigint("principal_balance_cents", { mode: "number" }).notNull(),
    interestRateBps: integer("interest_rate_bps").notNull(),
    // Payoff figure as of the statement's generated_at. Required by
    // §1026.41(d)(3)(iii) ("the amount required to pay the loan in full").
    payoffCents: bigint("payoff_cents", { mode: "number" }).notNull(),
    // Optional prepayment-penalty flag — required field but most AcreOS
    // notes carry none. We persist the boolean explicitly so the absence
    // is auditable (rather than relying on the PDF render to omit silently).
    prepaymentPenaltyDisclosed: boolean("prepayment_penalty_disclosed").notNull().default(false),

    // ── Past-payment breakdown — §1026.41(d)(4) ─────────────────────────
    // The previous cycle's split. JSONB to keep the row count flat and the
    // shape forward-compatible with optional-product columns we may add
    // (e.g. force-placed insurance).
    pastPaymentBreakdown: jsonb("past_payment_breakdown")
      .$type<{
        principalCents: number;
        interestCents: number;
        escrowCents: number;
        feesCents: number;
        unappliedCents: number;
        totalReceivedCents: number;
      }>()
      .notNull(),

    // ── Year-to-date totals — §1026.41(d)(4)(ii) ────────────────────────
    ytdPrincipalCents: bigint("ytd_principal_cents", { mode: "number" }).notNull().default(0),
    ytdInterestCents: bigint("ytd_interest_cents", { mode: "number" }).notNull().default(0),
    ytdEscrowCents: bigint("ytd_escrow_cents", { mode: "number" }).notNull().default(0),
    ytdFeesCents: bigint("ytd_fees_cents", { mode: "number" }).notNull().default(0),

    // ── Transaction activity — §1026.41(d)(5) ───────────────────────────
    // Every payment + fee from the prior cycle, in order. The renderer
    // walks this array; the persisted snapshot is the source of truth so
    // a borrower's re-download always matches what we sent originally.
    transactions: jsonb("transactions")
      .$type<
        Array<{
          date: string; // ISO yyyy-mm-dd
          label: string;
          amountCents: number; // signed: positive = received, negative = fee
          appliedTo: string; // 'principal/interest' | 'escrow' | 'late_fee' | 'suspense' | 'unapplied'
        }>
      >()
      .notNull(),

    // ── Partial-payment information — §1026.41(d)(7) ────────────────────
    // Only populated when suspense balance > 0 at cycle end. The statement
    // PDF must show the held amount + the disclaimer required by the rule.
    partialPaymentBalanceCents: bigint("partial_payment_balance_cents", { mode: "number" }).default(0),

    // ── Delinquency information — §1026.41(d)(8) ────────────────────────
    // Only populated when the borrower is >= 45 days delinquent. Includes
    // the date the account first became delinquent, current escalation
    // tier, and HUD-approved housing counsellor contact info (the rule
    // explicitly requires the HUD hotline 800-569-4287).
    delinquencyInfo: jsonb("delinquency_info").$type<{
      daysDelinquent: number;
      delinquentSinceDate: string;
      totalAmountDelinquentCents: number;
      housingCounselorPhone: string; // "800-569-4287"
      housingCounselorUrl: string; // HUD-approved search
      riskOfForeclosureNotice: boolean;
    }>(),

    // ── Generation + delivery state ─────────────────────────────────────
    generatedAt: timestamp("generated_at", { withTimezone: true }).defaultNow().notNull(),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    deliveryMethod: text("delivery_method"), // 'email' | 'portal_only' | 'mail' (future)
    deliveryStatus: text("delivery_status").notNull().default("pending"),
    // 'pending' | 'delivered' | 'bounced' | 'failed' | 'suppressed'
    deliveryError: text("delivery_error"),

    // S3 key of the rendered PDF. Render-on-demand is supported but caching
    // the rendered output once at generation time keeps re-download fast.
    pdfS3Key: text("pdf_s3_key"),

    // §1026.41(b) timing requirement: statement must be delivered no later
    // than 21 days before payment due. We persist the computed deadline
    // alongside the row so a missed-deadline event is auditable without
    // re-deriving from cycleStart.
    deliveryDeadline: date("delivery_deadline").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    // Borrower portal: "show me my last 24 statements for this loan", newest first.
    index("periodic_statements_loan_cycle_idx").on(table.loanId, table.cycleEnd),
    // Org-scoped admin views.
    index("periodic_statements_org_generated_idx").on(table.organizationId, table.generatedAt),
    // Idempotency guarantee — re-running the cron for a (loan, cycleStart)
    // is a no-op or replace, never a duplicate. §1026.41 requires exactly
    // one statement per billing cycle.
    uniqueIndex("periodic_statements_loan_cycle_uk").on(table.loanId, table.cycleStart),
  ],
);

export type PeriodicStatement = typeof periodicStatements.$inferSelect;
export type InsertPeriodicStatement = typeof periodicStatements.$inferInsert;

// ============================================================================
// §1026.36(c)(1) — PROMPT CREDITING + PAYMENT APPLICATION LEDGER
// ----------------------------------------------------------------------------
// 12 C.F.R. §1026.36(c)(1)(i): "no servicer shall fail to credit a
// periodic payment to the consumer's loan account as of the date of
// receipt." Our `appliedAt` column captures the credit-as-of date, which
// may differ from receivedAt only by the 5pm-local-time-on-due-date
// boundary that the rule permits.
// ============================================================================

export const paymentApplications = pgTable(
  "payment_applications",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: integer("organization_id")
      .references(() => organizations.id, { onDelete: "cascade" })
      .notNull(),
    loanId: text("loan_id").notNull(),
    loanType: text("loan_type").notNull().default("note"),
    // FK lives in app code, not at the DB layer, because paymentId may
    // point at `note_payments.id` (varchar uuid) or future payment tables.
    paymentId: text("payment_id").notNull(),

    // Wall-clock time the payment hit our system. The borrower's
    // payment-method timestamp, not the bank settlement timestamp.
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull(),
    // §1026.36(c)(1)(i): the as-of credit date. For most payments this
    // equals received_at; for payments received by 5pm local time on the
    // due date it remains the due date even if processing finishes later.
    appliedAt: timestamp("applied_at", { withTimezone: true }).notNull(),

    // Split — every cent of the payment lands in exactly one of these buckets.
    // Sum of buckets MUST equal the payment amount. Enforced in service code.
    appliedToPrincipalCents: bigint("applied_to_principal_cents", { mode: "number" })
      .notNull()
      .default(0),
    appliedToInterestCents: bigint("applied_to_interest_cents", { mode: "number" })
      .notNull()
      .default(0),
    appliedToEscrowCents: bigint("applied_to_escrow_cents", { mode: "number" })
      .notNull()
      .default(0),
    appliedToFeesCents: bigint("applied_to_fees_cents", { mode: "number" }).notNull().default(0),
    // §1026.36(c)(1)(ii): when a partial payment is received, the
    // servicer "may hold the payment in a suspense or unapplied funds
    // account". `appliedToSuspenseCents` records what flowed INTO the
    // suspense bucket on this transaction. Negative values mean we
    // RELEASED suspense funds (the matched-pair release entry).
    appliedToSuspenseCents: bigint("applied_to_suspense_cents", { mode: "number" })
      .notNull()
      .default(0),

    // The reg-citation that authorised this row's behaviour. Defaults to
    // the prompt-crediting clause but specific paths (suspense, partial,
    // late-fee allocation) override. Required field — a row without a
    // citation can't be reasoned about by a future Beatrice audit.
    regCitation: text("reg_citation").notNull().default("12 C.F.R. §1026.36(c)(1)(i)"),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("payment_applications_loan_applied_idx").on(table.loanId, table.appliedAt),
    index("payment_applications_org_applied_idx").on(table.organizationId, table.appliedAt),
    // One application row per payment — re-running the algorithm is idempotent.
    uniqueIndex("payment_applications_payment_uk").on(table.paymentId),
  ],
);

export type PaymentApplication = typeof paymentApplications.$inferSelect;
export type InsertPaymentApplication = typeof paymentApplications.$inferInsert;

// ============================================================================
// §1026.36(c)(1)(ii) — SUSPENSE BUCKET
// ----------------------------------------------------------------------------
// One row per loan; the running balance + the ledger of deposits and
// releases. We keep the running balance denormalised on this row (rather
// than always SUM-ing the ledger) so the payment-application algorithm
// can read-then-write atomically.
// ============================================================================

export const suspenseBalances = pgTable(
  "suspense_balances",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: integer("organization_id")
      .references(() => organizations.id, { onDelete: "cascade" })
      .notNull(),
    loanId: text("loan_id").notNull(),
    loanType: text("loan_type").notNull().default("note"),

    balanceCents: bigint("balance_cents", { mode: "number" }).notNull().default(0),
    lastUpdatedAt: timestamp("last_updated_at", { withTimezone: true }).defaultNow().notNull(),

    // Append-only ledger. Each entry: { at, delta, paymentId, kind, reason }.
    //   kind: 'deposit'  — partial payment landed in suspense
    //         'release'  — suspense funds released into P/I when full periodic accumulated
    //         'refund'   — manually returned to borrower (rare; needs ops note)
    // This ledger is the audit primitive a CFPB examiner sees.
    ledgerEntries: jsonb("ledger_entries")
      .$type<
        Array<{
          at: string;
          deltaCents: number;
          paymentId: string | null;
          kind: "deposit" | "release" | "refund";
          reason: string;
        }>
      >()
      .notNull()
      .default(sql`'[]'::jsonb`),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    // One row per loan — read path is "show me this loan's current suspense".
    uniqueIndex("suspense_balances_loan_uk").on(table.loanId),
    index("suspense_balances_org_idx").on(table.organizationId),
  ],
);

export type SuspenseBalance = typeof suspenseBalances.$inferSelect;
export type InsertSuspenseBalance = typeof suspenseBalances.$inferInsert;

// ============================================================================
// §1026.36(c)(2) — LATE-FEE NON-PYRAMIDING
// ----------------------------------------------------------------------------
// 12 C.F.R. §1026.36(c)(2): "no servicer shall impose any late fee or
// delinquency charge in connection with a periodic payment when the only
// delinquency is attributable to late fees or delinquency charges
// assessed on an earlier payment, and the periodic payment is otherwise
// a full periodic payment."
//
// Our enforcement: one row per (loan, cycle). Re-running the late-fee
// assessor for a cycle returns the existing row instead of duplicating.
// `justification` records the reg-cited reason the fee was authorised —
// a row that can't articulate WHY is a row a regulator will challenge.
// ============================================================================

export const lateFeeAssessments = pgTable(
  "late_fee_assessments",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: integer("organization_id")
      .references(() => organizations.id, { onDelete: "cascade" })
      .notNull(),
    loanId: text("loan_id").notNull(),
    loanType: text("loan_type").notNull().default("note"),

    // The CYCLE the fee is being assessed for — never the cycle in which
    // the borrower is paying. This is the core of non-pyramiding: the
    // fee attaches to the missed cycle, not to any later cycle.
    periodStart: date("period_start").notNull(),
    periodEnd: date("period_end").notNull(),

    // The payment (if any) that triggered the assessment. Null when the
    // assessor fires on the grace-period boundary with no payment yet.
    paymentId: text("payment_id"),

    feeAmountCents: bigint("fee_amount_cents", { mode: "number" }).notNull(),
    // Plain-English regulatory justification. Examples:
    //   "Cycle 2026-04 was not paid in full by due_date + grace_period
    //    of 10 days. Fee assessed per §1026.36(c)(2) on the missed
    //    cycle itself, not on subsequent cycles."
    justification: text("justification").notNull(),

    // Status. 'assessed' on creation; 'waived' if an ops user reverses;
    // 'reversed' if an NSF / mistake correction undoes it. Never 'deleted'
    // — the row stays for audit, only the status changes.
    status: text("status").notNull().default("assessed"),
    waivedAt: timestamp("waived_at", { withTimezone: true }),
    waivedBy: text("waived_by"),
    waivedReason: text("waived_reason"),

    assessedAt: timestamp("assessed_at", { withTimezone: true }).defaultNow().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    // Non-pyramiding guarantee: one fee row per (loan_type, loan, cycle).
    // The loan_type discriminator is REQUIRED in the key — distinct
    // originated notes + acquired notes can share an integer-vs-uuid id
    // collision space; without loanType in the index, a stringified
    // collision would silently de-duplicate two genuinely-distinct loans.
    // Beatrice piggyback (2026-06-02): the §1026.36(c)(2) non-pyramiding
    // guarantee must hold across the two loan-table boundary.
    uniqueIndex("late_fee_assessments_loan_period_uk").on(
      table.loanId,
      table.periodStart,
      table.loanType,
    ),
    index("late_fee_assessments_org_assessed_idx").on(table.organizationId, table.assessedAt),
  ],
);

export type LateFeeAssessment = typeof lateFeeAssessments.$inferSelect;
export type InsertLateFeeAssessment = typeof lateFeeAssessments.$inferInsert;

// ============================================================================
// §1026.41 — PERIODIC STATEMENT SKIPS (audit ledger)
// ----------------------------------------------------------------------------
// Per Beatrice's 2026-06-02 acquired-notes ruling: "A skip without a logged
// reason is indistinguishable from negligence." The predicate that gates
// statement generation (see server/services/periodicStatements/predicate.ts)
// MUST persist a row here every time it skips a (loan, cycle) — with the
// §-citation that authorised the skip. When a CFPB examiner asks "why didn't
// AcreOS send a statement for loan X in April," the ledger IS the answer.
//
// Append-only contract: no UPDATE / DELETE in production code paths. The
// monotonic ledger is the audit primitive.
//
// The polymorphic note_table discriminator lets one ledger cover both the
// originated `notes` flow and the new `acquired_notes` flow without a
// migration-per-vertical proliferation.
// ============================================================================

export const periodicStatementSkips = pgTable(
  "periodic_statement_skips",
  {
    // bigserial in prod (mirrors `id BIGSERIAL` in migrate.mjs); Drizzle's
    // bigint+identity is the closest match.
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    organizationId: integer("org_id")
      .references(() => organizations.id, { onDelete: "cascade" })
      .notNull(),
    // Polymorphic — points at either `notes.id` (integer cast to text) or
    // `acquired_notes.id` (uuid). Discriminator below tells the resolver
    // which table the id belongs to.
    noteId: text("note_id").notNull(),
    noteTable: text("note_table").notNull(), // 'notes' | 'acquired_notes'

    cycleStart: timestamp("cycle_start", { withTimezone: true }).notNull(),

    // Plain-English reason a future Beatrice audit reads at a glance.
    reason: text("reason").notNull(),
    // The §-section that AUTHORISED the skip. Required field — never silent.
    citation: text("citation").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    // Idempotency: re-running the cron for a (org, table, note, cycle) is
    // a no-op at the DB layer. ON CONFLICT DO NOTHING in the writer.
    uniqueIndex("periodic_statement_skips_org_table_note_cycle_uk").on(
      table.organizationId,
      table.noteTable,
      table.noteId,
      table.cycleStart,
    ),
    // Audit read path: "show me every skip this org logged in the last quarter."
    index("periodic_statement_skips_org_created_idx").on(table.organizationId, table.createdAt),
  ],
);

export type PeriodicStatementSkip = typeof periodicStatementSkips.$inferSelect;
export type InsertPeriodicStatementSkip = typeof periodicStatementSkips.$inferInsert;
