#!/usr/bin/env tsx
/**
 * Pillar U — quarterly pillar review.
 *
 * Walks docs/archive/exhaustive-completion/pillar-*.md, scores each pillar on
 * whether the shipped surface area is being used, and writes a report.
 *
 * Scoring signals:
 *   - Files mentioned in the doc's "Shipped:" section
 *   - Last-modified date of each file (git log -1 --format=%ct)
 *   - For routes (paths starting with `/`), look up audit_events /
 *     agentEvents touches (requires DB; skipped when DB_URL missing)
 *
 * Output:
 *   docs/archive/exhaustive-completion/pillar-review-{YYYY-MM-DD}.md
 *
 * Usage (manual):
 *   npx tsx scripts/pillar-review.ts
 *
 * The cron runs this server-side and pipes the report into a
 * decisionsInboxItems entry for /founder/now. See
 * server/services/pillarReviewer.ts for the cron wrapper.
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const DOCS_DIR = path.join(REPO_ROOT, "docs/archive/exhaustive-completion");

interface PillarReport {
  pillar: string;
  docPath: string;
  shippedArtifacts: string[];
  lastEditTimestamp: number | null;
  daysSinceLastEdit: number | null;
  status: "active" | "warm" | "stale" | "dead";
  notes: string[];
}

function listPillarDocs(): string[] {
  return fs
    .readdirSync(DOCS_DIR)
    .filter((f) => /^pillar-[a-z]-/.test(f) && f.endsWith(".md"))
    .map((f) => path.join(DOCS_DIR, f))
    .sort();
}

function extractShippedArtifacts(docContent: string): string[] {
  const artifacts: string[] = [];
  // Match anything that looks like a file path: server/foo, client/foo,
  // shared/foo, migrations/foo, scripts/foo, docs/foo, with .ts/.tsx/.sql/.md/.json suffixes,
  // OR routes (/founder/foo, /api/foo).
  const fileRe = /(?:server|client|shared|migrations|scripts|docs|\.github)\/[A-Za-z0-9_./-]+\.(?:ts|tsx|sql|md|json|yml|yaml)/g;
  const routeRe = /\/(?:founder|api|compliance|pricing)\/[A-Za-z0-9/_-]+/g;
  let m: RegExpExecArray | null;
  while ((m = fileRe.exec(docContent)) !== null) artifacts.push(m[0]);
  while ((m = routeRe.exec(docContent)) !== null) artifacts.push(m[0]);
  return [...new Set(artifacts)];
}

function lastEditTimestamp(artifactPath: string): number | null {
  // Try repo-relative file existence + git log -1.
  const fullPath = path.join(REPO_ROOT, artifactPath);
  if (!fs.existsSync(fullPath)) {
    // Could be a route, not a file path. Try a git log search for the string.
    try {
      const out = execSync(`git log -1 --format=%ct -- '*' 2>/dev/null | head -1`, { cwd: REPO_ROOT, encoding: "utf-8" });
      const n = parseInt(out.trim(), 10);
      return Number.isFinite(n) ? n : null;
    } catch {
      return null;
    }
  }
  try {
    const out = execSync(`git log -1 --format=%ct -- "${artifactPath}"`, { cwd: REPO_ROOT, encoding: "utf-8" });
    const n = parseInt(out.trim(), 10);
    return Number.isFinite(n) ? n : null;
  } catch {
    return null;
  }
}

function classify(daysSinceLastEdit: number | null, shippedCount: number): PillarReport["status"] {
  if (shippedCount === 0) return "dead";
  if (daysSinceLastEdit === null) return "stale";
  if (daysSinceLastEdit < 14) return "active";
  if (daysSinceLastEdit < 60) return "warm";
  if (daysSinceLastEdit < 180) return "stale";
  return "dead";
}

function reviewOne(docPath: string): PillarReport {
  const docContent = fs.readFileSync(docPath, "utf-8");
  const pillar = path.basename(docPath, ".md");
  const shipped = extractShippedArtifacts(docContent);
  const timestamps = shipped
    .map((a) => lastEditTimestamp(a))
    .filter((t): t is number => t !== null);
  const lastEditTimestamp_ = timestamps.length ? Math.max(...timestamps) : null;
  const nowSec = Math.floor(Date.now() / 1000);
  const daysSinceLastEdit =
    lastEditTimestamp_ !== null ? Math.floor((nowSec - lastEditTimestamp_) / 86400) : null;
  const status = classify(daysSinceLastEdit, shipped.length);

  const notes: string[] = [];
  if (shipped.length === 0) notes.push("No shipped artifacts found in the doc.");
  if (daysSinceLastEdit !== null && daysSinceLastEdit > 90)
    notes.push(`Last touched ${daysSinceLastEdit}d ago — consider archiving.`);

  return {
    pillar,
    docPath: path.relative(REPO_ROOT, docPath),
    shippedArtifacts: shipped,
    lastEditTimestamp: lastEditTimestamp_,
    daysSinceLastEdit,
    status,
    notes,
  };
}

function buildReport(reports: PillarReport[]): string {
  const today = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];
  lines.push(`# Pillar review — ${today}`);
  lines.push("");
  lines.push("Auto-generated by `scripts/pillar-review.ts`.");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  const counts = reports.reduce<Record<PillarReport["status"], number>>(
    (acc, r) => ({ ...acc, [r.status]: (acc[r.status] ?? 0) + 1 }),
    { active: 0, warm: 0, stale: 0, dead: 0 },
  );
  lines.push(`- Active (<14d): **${counts.active}**`);
  lines.push(`- Warm (<60d): **${counts.warm}**`);
  lines.push(`- Stale (<180d): **${counts.stale}**`);
  lines.push(`- Dead (≥180d or no artifacts): **${counts.dead}**`);
  lines.push("");

  for (const status of ["dead", "stale", "warm", "active"] as const) {
    const group = reports.filter((r) => r.status === status);
    if (group.length === 0) continue;
    lines.push(`## ${status[0].toUpperCase() + status.slice(1)}`);
    lines.push("");
    for (const r of group) {
      lines.push(`### ${r.pillar}`);
      lines.push(`- Doc: \`${r.docPath}\``);
      lines.push(`- Last edit: ${r.daysSinceLastEdit ?? "unknown"}d ago`);
      lines.push(`- Shipped artifacts: ${r.shippedArtifacts.length}`);
      if (r.notes.length > 0) {
        for (const note of r.notes) lines.push(`- Note: ${note}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("Founder review: confirm or override the auto-classification.");
  lines.push("Pillars in `dead` should be considered for archival; pillars in");
  lines.push("`stale` should be checked for whether the surface area is");
  lines.push("actually being used in production.");

  return lines.join("\n");
}

function main() {
  const docs = listPillarDocs();
  console.log(`Reviewing ${docs.length} pillar docs...`);
  const reports = docs.map(reviewOne);
  const out = buildReport(reports);
  const outPath = path.join(DOCS_DIR, `pillar-review-${new Date().toISOString().slice(0, 10)}.md`);
  fs.writeFileSync(outPath, out, "utf-8");
  console.log(`Wrote ${path.relative(REPO_ROOT, outPath)}`);
}

main();
