#!/usr/bin/env node
/**
 * DomainPack SCAFFOLDER (Frontier #11).
 *
 * Generates a new vertical pack skeleton that already refines the kernel
 * contract (passes admitPack) — so onboarding a second vertical is "fill in your
 * causal theory + regulatory rules", not "reverse-engineer the seam." The
 * skeleton ships a minimal-but-VALID causal model (one lever → one outcome) and
 * an empty-but-well-formed regulatory profile, then admitPack admits it on day
 * one; you replace the stubs with the vertical's real theory.
 *
 *     node scripts/scaffold-pack.mjs <pack-id>     # prints the files
 *     node scripts/scaffold-pack.mjs <pack-id> --write   # writes packs/<id>/
 *
 * Pure generation — no network, no deps. --write refuses to clobber an existing
 * pack dir (fail-safe).
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const KEBAB = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

function pascal(id) {
  return id.split("-").map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");
}
function constCase(id) {
  return id.replace(/-/g, "_").toUpperCase();
}

export function scaffoldPackFiles(id) {
  if (!KEBAB.test(id)) throw new Error(`pack id must be lowercase kebab-case, got "${id}"`);
  const C = constCase(id); // e.g. SOLAR
  const P = pascal(id); // e.g. Solar
  const causalModel = `/**
 * ${P} pack — causal theory of the business. Replace these placeholder
 * variables + edges with the vertical's real levers, metrics, and outcome.
 * Edge confidences start LOW (priors); the experience ledger sharpens them.
 */
import type { CausalModel } from "../../worldModel";

export const ${C}_CAUSAL_MODEL: CausalModel = {
  version: 1,
  variables: [
    { id: "primary_action", label: "Primary action", kind: "lever" },
    { id: "engagement", label: "Engagement", kind: "metric" },
    { id: "revenue", label: "Revenue", kind: "outcome" },
  ],
  edges: [
    { from: "primary_action", to: "engagement", effect: 0.5, confidence: 0.2, evidence: "prior" },
    { from: "engagement", to: "revenue", effect: 0.3, confidence: 0.2, evidence: "prior" },
  ],
};

/** Maps a decide.ts move-kind to the lever it pulls. A move with no entry has
 *  "no causal model yet" — honest absence, never a faked estimate. */
export const ${C}_MOVE_TO_LEVER: Record<string, string> = {
  // example_move: "primary_action",
};
`;

  const regulatoryProfile = `/**
 * ${P} pack — content-regulatory rules the kernel claims engine screens
 * auto-published content against. Start empty-but-well-formed; add the
 * vertical's prohibited-claim patterns + required disclosures.
 */
import type { RegulatoryProfile } from "../../claimsEngine";

export const ${C}_REGULATORY_PROFILE: RegulatoryProfile = {
  attributionCues: [],
  determinationPatterns: [],
  bannedPatterns: [],
  disclosureCues: [],
};
`;

  const index = `/**
 * ${P} DomainPack — the typed kernel↔vertical seam for the ${id} vertical.
 * Generated by scripts/scaffold-pack.mjs; passes admitPack on day one. Replace
 * the placeholder causal theory with the vertical's real model.
 */
import type { DomainPack } from "../../domainPack";
import { ${C}_CAUSAL_MODEL, ${C}_MOVE_TO_LEVER } from "./causalModel";
import { ${C}_REGULATORY_PROFILE } from "./regulatoryProfile";

export const ${C}_PACK: DomainPack = {
  id: "${id}",
  label: "${P}",
  causalModel: ${C}_CAUSAL_MODEL,
  moveToLever: ${C}_MOVE_TO_LEVER,
  regulatoryProfile: ${C}_REGULATORY_PROFILE,
};
`;

  return {
    [`packs/${id}/causalModel.ts`]: causalModel,
    [`packs/${id}/regulatoryProfile.ts`]: regulatoryProfile,
    [`packs/${id}/index.ts`]: index,
  };
}

function main(argv) {
  const id = argv[2];
  const write = argv.includes("--write");
  if (!id) {
    process.stderr.write("usage: node scripts/scaffold-pack.mjs <pack-id> [--write]\n");
    return 2;
  }
  let files;
  try {
    files = scaffoldPackFiles(id);
  } catch (err) {
    process.stderr.write(`[scaffold-pack] ${err?.message ?? err}\n`);
    return 2;
  }
  if (!write) {
    for (const [path, content] of Object.entries(files)) {
      process.stdout.write(`\n=== ${path} ===\n${content}`);
    }
    process.stdout.write(`\n[scaffold-pack] dry run — pass --write to create server/services/autopilot/packs/${id}/\n`);
    return 0;
  }
  const root = join("server", "services", "autopilot", "packs", id);
  if (existsSync(root)) {
    process.stderr.write(`[scaffold-pack] refusing to clobber existing pack dir: ${root}\n`);
    return 1;
  }
  mkdirSync(root, { recursive: true });
  for (const [rel, content] of Object.entries(files)) {
    writeFileSync(join("server", "services", "autopilot", rel), content, "utf8");
  }
  process.stdout.write(`[scaffold-pack] wrote ${Object.keys(files).length} files to ${root} — wire it into resolveActivePack, then run admitPack.\n`);
  return 0;
}

import { fileURLToPath } from "node:url";
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv));
}
