/**
 * External Communications Manager — Sovereign Company Protocol Phase 17
 *
 * Stakeholder communications, public communications, crisis comms protocol,
 * and communication consistency engine.
 */

import { db } from "../db";
import { agentActionLog, organizations } from "@shared/schema";
import { eq, desc, sql, count } from "drizzle-orm";
import crypto from "crypto";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Communication {
  id: string;
  type: "investor_update" | "board_deck" | "blog_post" | "press_release" | "social_post" | "status_page" | "customer_notification";
  title: string;
  content: string;
  audience: string;
  complianceApproved: boolean;
  status: "draft" | "review" | "approved" | "published";
  channel: string;
  createdAt: string;
  publishedAt?: string;
}

interface BrandVoiceGuidelines {
  tone: string[];
  vocabulary: { preferred: string[]; avoid: string[] };
  principles: string[];
}

// ─── In-Memory State ──────────────────────────────────────────────────────────

const communications: Map<string, Communication> = new Map();

const BRAND_VOICE: BrandVoiceGuidelines = {
  tone: [
    "Professional but approachable",
    "Data-driven and specific",
    "Empathetic when addressing issues",
    "Confident without being arrogant",
    "Direct and action-oriented",
  ],
  vocabulary: {
    preferred: ["land investors", "portfolio", "due diligence", "returns", "opportunity", "streamline", "automate"],
    avoid: ["guaranteed returns", "get rich", "no risk", "limited time", "act now", "crypto"],
  },
  principles: [
    "Always lead with value for the reader",
    "Include specific numbers and data when possible",
    "Never make promises about financial returns",
    "Maintain regulatory compliance in all communications",
    "Be transparent about limitations and risks",
  ],
};

// ─── Service ──────────────────────────────────────────────────────────────────

class ExternalCommunicationsManager {

  // ─── Stakeholder Communications ───────────────────────────────────────────

  /**
   * Generate monthly investor update using Founder Twin voice + Ledger metrics.
   */
  async generateInvestorUpdate(period: string): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;

    // Gather metrics from Ledger and Forge
    const { resolveAgentData } = await import("./agentDataResolvers");
    const [forgeData, ledgerData] = await Promise.all([
      resolveAgentData("forge_revenue"),
      resolveAgentData("ledger_finance"),
    ]);

    // Get founder voice style
    let founderStyle = "";
    try {
      const { founderTwinService } = await import("./founderTwin");
      founderStyle = await founderTwinService.getStyleProfile();
    } catch {}

    const content = `# Investor Update — ${period}

## Revenue Highlights
- MRR: $${forgeData.mrrDollars || "N/A"}
- ARR: $${forgeData.arrDollars || "N/A"}
- Paying Organizations: ${forgeData.payingOrgs || "N/A"}
- Churn Rate (30d): ${forgeData.churnRate30d || "N/A"}%

## Financial Health
- AI Spend (7d): $${ledgerData.aiSpend7dDollars || "N/A"}
- AI Cost per Org: $${((ledgerData.aiCostPerOrgCents || 0) / 100).toFixed(2)}

## Product & Growth
- Active Organizations: ${forgeData.activeOrgs || "N/A"}
- New Signups This Period: Recent activity positive

## Looking Ahead
The team continues to execute on our strategic priorities. The autonomous agent system is operational and handling daily decisions independently.

---
*Generated by AcreOS AI Board of Directors*`;

    const comm: Communication = {
      id,
      type: "investor_update",
      title: `Investor Update — ${period}`,
      content,
      audience: "investors",
      complianceApproved: false,
      status: "draft",
      channel: "email",
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    await this.logCommunication("forge_revenue", "generate_investor_update", { period }, { id });
    return comm;
  }

  /**
   * Generate board deck with real-time metrics.
   */
  async generateBoardDeck(period: string): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;

    const { resolveAgentData } = await import("./agentDataResolvers");
    const metrics: Record<string, any> = {};

    const agents = ["forge_revenue", "ledger_finance", "oracle_analytics", "sophie_csm", "atlas_cto"];
    for (const agent of agents) {
      try {
        metrics[agent] = await resolveAgentData(agent);
      } catch {}
    }

    const comm: Communication = {
      id,
      type: "board_deck",
      title: `Board Deck — ${period}`,
      content: JSON.stringify({
        period,
        sections: [
          { title: "Financial Summary", data: metrics.forge_revenue || {}, presenter: "ledger_finance" },
          { title: "Product Health", data: metrics.atlas_cto || {}, presenter: "atlas_cto" },
          { title: "Customer Health", data: metrics.sophie_csm || {}, presenter: "sophie_csm" },
          { title: "Growth Analytics", data: metrics.oracle_analytics || {}, presenter: "oracle_analytics" },
          { title: "AI Cost Analysis", data: metrics.ledger_finance || {}, presenter: "ledger_finance" },
        ],
      }),
      audience: "board_members",
      complianceApproved: false,
      status: "draft",
      channel: "internal",
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    return comm;
  }

  async getRecentUpdates(type?: string, limit: number = 10): Promise<Communication[]> {
    let comms = Array.from(communications.values());
    if (type) comms = comms.filter(c => c.type === type);
    return comms.sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit);
  }

  // ─── Public Communications ────────────────────────────────────────────────

  /**
   * Draft a blog post on a topic.
   */
  async draftBlogPost(topic: string, targetAudience: string = "land investors"): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;

    const comm: Communication = {
      id,
      type: "blog_post",
      title: topic,
      content: `# ${topic}\n\nContent for ${targetAudience}.\n\n*Draft generated by Beacon Marketing. Pending Shield compliance review.*`,
      audience: targetAudience,
      complianceApproved: false,
      status: "draft",
      channel: "blog",
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    await this.logCommunication("beacon_marketing", "draft_blog_post", { topic, targetAudience }, { id });
    return comm;
  }

  /**
   * Draft a press release.
   */
  async draftPressRelease(announcement: string): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;

    const comm: Communication = {
      id,
      type: "press_release",
      title: announcement,
      content: `FOR IMMEDIATE RELEASE\n\n${announcement}\n\n*Draft pending Shield compliance review.*`,
      audience: "media",
      complianceApproved: false,
      status: "draft",
      channel: "press",
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    return comm;
  }

  /**
   * Draft a social media post.
   */
  async draftSocialPost(platform: "twitter" | "linkedin", topic: string): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;
    const maxLength = platform === "twitter" ? 280 : 1500;

    const comm: Communication = {
      id,
      type: "social_post",
      title: `${platform}: ${topic}`,
      content: topic.slice(0, maxLength),
      audience: "public",
      complianceApproved: false,
      status: "draft",
      channel: platform,
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    return comm;
  }

  /**
   * Shield reviews content for compliance issues.
   */
  async reviewForCompliance(contentId: string, contentType: string): Promise<{ approved: boolean; issues: string[] }> {
    const comm = communications.get(contentId);
    if (!comm) return { approved: false, issues: ["Communication not found"] };

    const issues: string[] = [];
    const content = comm.content.toLowerCase();

    // Check for prohibited language
    for (const word of BRAND_VOICE.vocabulary.avoid) {
      if (content.includes(word.toLowerCase())) {
        issues.push(`Contains prohibited term: "${word}"`);
      }
    }

    // Check for financial promises
    if (content.includes("guarantee") && (content.includes("return") || content.includes("profit"))) {
      issues.push("Contains language that could constitute a financial guarantee");
    }

    // Check for PII
    const emailRegex = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;
    if (emailRegex.test(comm.content)) {
      issues.push("Contains email addresses — potential PII exposure");
    }

    const approved = issues.length === 0;
    comm.complianceApproved = approved;
    comm.status = approved ? "approved" : "review";
    communications.set(contentId, comm);

    await this.logCommunication("shield_legal", "review_compliance", { contentId, contentType }, { approved, issues });
    return { approved, issues };
  }

  /**
   * Publish content after compliance approval.
   */
  async publishContent(contentId: string, channel: string): Promise<{ success: boolean; message: string }> {
    const comm = communications.get(contentId);
    if (!comm) return { success: false, message: "Communication not found" };
    if (!comm.complianceApproved) return { success: false, message: "Content not compliance-approved by Shield" };

    comm.status = "published";
    comm.publishedAt = new Date().toISOString();
    comm.channel = channel;
    communications.set(contentId, comm);

    await this.logCommunication("beacon_marketing", "publish_content", { contentId, channel }, { published: true });
    return { success: true, message: `Published "${comm.title}" to ${channel}` };
  }

  // ─── Crisis Communication Protocol ────────────────────────────────────────

  /**
   * Coordinate crisis communications across all channels.
   */
  async initiateCrisisComms(crisisType: string, severity: string, details: string): Promise<{
    statusPageUpdate: Communication;
    customerNotification: Communication;
    actions: string[];
  }> {
    const actions: string[] = [];

    // 1. Status page update
    const statusUpdate = await this.draftStatusPageUpdate(crisisType, severity);
    actions.push(`Status page draft created: ${statusUpdate.id}`);

    // 2. Customer notification (for affected orgs)
    const customerNotif = await this.draftCustomerNotification(crisisType, []);
    actions.push(`Customer notification draft created: ${customerNotif.id}`);

    // 3. Check if regulatory notification needed
    const regReqs = this.getRegulatoryNotificationRequirements(crisisType);
    if (regReqs.length > 0) {
      actions.push(`Regulatory notifications required: ${regReqs.join(", ")}`);
    }

    // 4. Broadcast to agents
    try {
      const { agentCommsService } = await import("./agentComms");
      await agentCommsService.broadcast({
        from: "shield_legal",
        channel: "incidents",
        priority: "critical",
        subject: `CRISIS COMMS INITIATED: ${crisisType}`,
        body: `Severity: ${severity}. ${details}. Status page and customer notifications being prepared.`,
        data: { crisisType, severity, statusPageId: statusUpdate.id, customerNotifId: customerNotif.id },
      });
    } catch {}

    return { statusPageUpdate: statusUpdate, customerNotification: customerNotif, actions };
  }

  /**
   * Draft a status page update.
   */
  async draftStatusPageUpdate(incident: string, severity: string): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;
    const statusMap: Record<string, string> = {
      critical: "Major System Disruption",
      high: "Partial Service Degradation",
      medium: "Minor Service Impact",
      low: "Informational Notice",
    };

    const comm: Communication = {
      id,
      type: "status_page",
      title: statusMap[severity] || "Service Notice",
      content: `**${statusMap[severity] || "Service Notice"}**\n\n${incident}\n\nWe are actively investigating and will provide updates as we learn more.\n\nLast updated: ${new Date().toISOString()}`,
      audience: "technical",
      complianceApproved: true, // Status page updates auto-approved for speed
      status: "approved",
      channel: "status_page",
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    return comm;
  }

  /**
   * Draft customer notification for affected organizations.
   */
  async draftCustomerNotification(incident: string, affectedOrgIds: number[]): Promise<Communication> {
    const id = `comm-${crypto.randomUUID().slice(0, 8)}`;

    const comm: Communication = {
      id,
      type: "customer_notification",
      title: `Service Update: ${incident}`,
      content: `We're reaching out to let you know about a service issue that may have affected your account.\n\n**What happened:** ${incident}\n\n**Impact:** We're assessing the full impact and will update you shortly.\n\n**What we're doing:** Our team is actively working to resolve this. No action is required on your part.\n\nWe apologize for any inconvenience and appreciate your patience.\n\n— The AcreOS Team`,
      audience: `${affectedOrgIds.length || "all"} organizations`,
      complianceApproved: false,
      status: "draft",
      channel: "email",
      createdAt: new Date().toISOString(),
    };

    communications.set(id, comm);
    return comm;
  }

  /**
   * Check if regulatory notification is required for an incident type.
   */
  getRegulatoryNotificationRequirements(incidentType: string): string[] {
    const requirements: string[] = [];
    const type = incidentType.toLowerCase();

    if (type.includes("data breach") || type.includes("security")) {
      requirements.push("State data breach notification laws (varies by state, typically 30-72 hours)");
      requirements.push("FTC notification if >500 individuals affected");
    }
    if (type.includes("financial") || type.includes("payment")) {
      requirements.push("PCI DSS incident response procedures");
    }
    if (type.includes("gdpr") || type.includes("privacy")) {
      requirements.push("GDPR Article 33: Supervisory authority notification within 72 hours");
      requirements.push("GDPR Article 34: Data subject notification if high risk");
    }

    return requirements;
  }

  // ─── Communication Consistency Engine ─────────────────────────────────────

  /**
   * Get brand voice guidelines.
   */
  getBrandVoiceGuidelines(): BrandVoiceGuidelines {
    return BRAND_VOICE;
  }

  /**
   * Check content matches brand voice.
   */
  checkBrandConsistency(content: string): { consistent: boolean; issues: string[] } {
    const issues: string[] = [];
    const lower = content.toLowerCase();

    for (const word of BRAND_VOICE.vocabulary.avoid) {
      if (lower.includes(word.toLowerCase())) {
        issues.push(`Uses avoided term: "${word}"`);
      }
    }

    if (content.length > 50 && !content.includes(".") && !content.includes("!")) {
      issues.push("Content appears to lack proper sentence structure");
    }

    return { consistent: issues.length === 0, issues };
  }

  /**
   * Get pre-approved messaging for common topics.
   */
  getApprovedMessaging(topic: string): string | null {
    const approvedTopics: Record<string, string> = {
      pricing: "AcreOS offers flexible pricing tiers designed for land investors at every stage. Visit our pricing page for current plans.",
      security: "AcreOS uses industry-standard encryption, SOC 2 compliant practices, and regular security audits to protect your data.",
      uptime: "AcreOS maintains 99.9%+ uptime with redundant infrastructure and automated failover systems.",
      support: "Our support team is available via in-app chat, email, and phone during business hours. Premium plans include priority support.",
      refund: "Please contact our support team to discuss your account. We handle each request on a case-by-case basis.",
    };

    return approvedTopics[topic.toLowerCase()] || null;
  }

  // ─── Utility ──────────────────────────────────────────────────────────────

  private async logCommunication(agent: string, action: string, input: any, output: any): Promise<void> {
    try {
      await db.insert(agentActionLog).values({
        agentCodename: agent,
        actionType: "proactive",
        actionName: action,
        input,
        output,
        reasoning: `External communication: ${action}`,
        confidence: 80,
        authorityLevel: 0,
        trustScoreAtTime: 0,
        outcome: "success",
        durationMs: 0,
      });
    } catch {}
  }

  /**
   * Get all communications for dashboard.
   */
  getAllCommunications(limit: number = 50): Communication[] {
    return Array.from(communications.values())
      .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
      .slice(0, limit);
  }
}

export const externalCommsManager = new ExternalCommunicationsManager();
