/**
 * L1 — liability-shield disclaimer legends for generated artifacts.
 *
 * Single source of truth for the standing "informational, not advice"
 * legends embedded into every artifact AcreOS generates (score reports,
 * worksheets, statements, document templates, AI output). Mirrors the
 * pattern of `TAX_ADVISORY_COPY` (server/utils/taxAdvisory.ts),
 * `SCREENING_ADVISORY_COPY` (compliance/ofacScreening.ts), and the
 * rmloAdvisor `DISCLAIMER` (shared/regulatory/rmloAdvisor.ts): one
 * centralized string per artifact class so the non-advice framing is
 * identical everywhere it surfaces.
 *
 * Vocabulary is drawn from docs/legal/terms-of-service.md ("AcreOS is not
 * a broker, lender, servicer, real estate agent, investment adviser, or
 * fiduciary… does not provide legal, financial, investment, or tax
 * advice") — reuse these constants rather than inventing new phrasings.
 *
 * These constants only ADD text to artifacts. They never gate, block, or
 * rewrite any generated output.
 */

/**
 * Land Credit Score surfaces (in-app LCS report PDF, public partial-score
 * parcel report). The score reads like a consumer credit score by design —
 * this legend makes explicit that it is not one.
 */
export const DISCLAIMER_INFORMATIONAL_SCORE =
  "The Land Credit Score is an informational property analysis produced by AcreOS software. " +
  "It scores the parcel, not a person: it is not a consumer credit score, is not a consumer report, " +
  "is not governed by the Fair Credit Reporting Act (FCRA), and is not lending or investment advice. " +
  "AcreOS is not a broker, lender, servicer, real estate agent, investment adviser, or fiduciary.";

/**
 * Servicing / tax / due-diligence worksheets and computed statements —
 * anything that presents figures derived from data supplied to the
 * platform.
 */
export const DISCLAIMER_WORKSHEET =
  "This is an informational worksheet generated by AcreOS software from data provided to it. " +
  "It may be incomplete or contain errors — verify every figure independently and with your attorney " +
  "or CPA before relying on it. AcreOS is not your servicer, lender, broker, or adviser and does not " +
  "provide legal, financial, investment, or tax advice.";

/**
 * Generated legal documents (promissory notes, deeds, assignments, land
 * contracts, offer letters). These are templates, not counsel work-product.
 */
export const DISCLAIMER_DOCUMENT_TEMPLATE =
  "This generated document is a template for review by you and your attorney before any use. " +
  "AcreOS does not practice law and this is not legal advice; recordability and enforceability " +
  "vary by state and county. Have a licensed attorney in the relevant jurisdiction review this " +
  "document before signing, sending, or recording it.";

/**
 * AI-generated content of any kind. Matches the client-side
 * RequiredDisclaimer "ai" variant framing.
 */
export const DISCLAIMER_AI =
  "AI-generated content is for informational purposes only and may contain errors. " +
  "Review and verify it independently before acting on it. AcreOS is not a fiduciary and does not " +
  "provide legal, financial, investment, or tax advice.";
