// @vitest-environment jsdom
/**
 * Wave D2 client surface — accepted offer → purchase agreement → e-sign,
 * inside the Deals door (the Contracts tab of /offers).
 *
 * The invariant under test is the FOUNDER HARD-STOP, not the layout:
 * `legal_signing` is founder-only forever, so the chain must be three
 * separate human acts. These tests pin, in order:
 *
 *   1. mounting the surface writes nothing and sends nothing;
 *   2. opening the review step is a READ — still no write, no send;
 *   3. the draft is created only after an explicit confirmation of the exact
 *      content shown, and the POST carries that content's sha256;
 *   4. the signing rail is reached only by a further, separate click;
 *   5. a state with no reviewed template REFUSES BY NAME and offers no
 *      document at all — no generic fallback.
 *
 * The fixtures are generated by the REAL assembler
 * (server/services/contracts/contractAssembly.ts — a pure module: no db, no
 * express, no logger), so the content, the hash and the refusal wording are
 * the server's own, not a hand-written imitation. No DATABASE_URL needed.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import React from "react";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Router } from "wouter";

import {
  assembleContract,
  resolveStateContractTemplate,
} from "../../server/services/contracts/contractAssembly";
import { ContractChainSection } from "../../client/src/pages/offers";

// ── real assembled draft for a Georgia deal ────────────────────────────────

const DEAL_ID = 12;
const DOCUMENT_ID = 55;

const assembled = assembleContract({
  kind: "purchase_agreement",
  organizationName: "Peachtree Holdings",
  deal: {
    id: DEAL_ID,
    status: "accepted",
    type: "acquisition",
    acceptedAmount: "182500.00",
    closingDate: new Date("2026-09-15T00:00:00.000Z"),
  },
  property: {
    id: 7,
    apn: "17-0123-0001",
    address: "1247 Cherokee Pl",
    city: "Atlanta",
    state: "GA",
    county: "Fulton",
    zip: "30315",
    sizeAcres: "0.21",
    legalDescription: "Lot 14, Block C, Cherokee Heights, Plat Book 22, Page 41",
  },
  seller: { legalName: "Dolores Whitfield", email: "dolores@example.com" },
  buyer: {
    legalName: "Peachtree Holdings LLC",
    email: "offers@example.com",
    address: "100 Peachtree St, Atlanta, GA",
  },
});

if (!assembled.ok) {
  throw new Error(
    `fixture setup: the Georgia purchase agreement should assemble — got ${assembled.refusal.code}`,
  );
}
const draft = assembled.draft;

/** The server's own refusal for a state with no reviewed template. */
const wyomingRefusal = resolveStateContractTemplate("WY", "purchase_agreement");
if (wyomingRefusal.ok) {
  throw new Error("fixture setup: WY must NOT be contract-ready");
}
const WY_REFUSAL = wyomingRefusal.refusal;

const deal = {
  id: DEAL_ID,
  organizationId: 1,
  propertyId: 7,
  type: "acquisition",
  status: "accepted",
  acceptedAmount: "182500.00",
  closingDate: new Date("2026-09-15T00:00:00.000Z"),
};

const property = { id: 7, address: "1247 Cherokee Pl", state: "GA" };

// ── fetch mock ─────────────────────────────────────────────────────────────

const state = { previewRefusesWithWyoming: false };
let calls: Array<{ method: string; url: string; body: unknown }> = [];

function json(body: unknown, status = 200): Promise<Response> {
  return Promise.resolve(
    new Response(JSON.stringify(body), {
      status,
      headers: { "Content-Type": "application/json" },
    }),
  );
}

function fetchMock(url: string, init?: RequestInit): Promise<Response> {
  const method = (init?.method ?? "GET").toUpperCase();
  const body = init?.body ? JSON.parse(String(init.body)) : null;
  calls.push({ method, url, body });

  if (url.includes("/contract-preview")) {
    if (state.previewRefusesWithWyoming) {
      // Exactly what Errors.validationFailed(res, refusal) puts on the wire.
      return json(
        {
          error: "VALIDATION_FAILED",
          message: "Some fields need a fix:",
          details: WY_REFUSAL,
          statusCode: 422,
        },
        422,
      );
    }
    return json({
      kind: draft.kind,
      title: draft.title,
      name: draft.name,
      state: draft.state,
      stateName: draft.stateName,
      content: draft.content,
      contentHash: draft.contentHash,
      variables: draft.variables,
      stateRequirements: draft.stateRequirements,
      signerRoles: draft.signerRoles,
      advisories: draft.advisories,
      disclaimer: draft.disclaimer,
      assignmentId: null,
      sent: false,
      hardStop: "legal_signing",
    });
  }
  if (url === `/api/deals/${DEAL_ID}/contract`) {
    return json(
      {
        document: { id: DOCUMENT_ID, name: draft.name },
        sent: false,
        signerRoles: draft.signerRoles,
        nextStep: {
          action: "request-signature",
          endpoint: `/api/generated-documents/${DOCUMENT_ID}/request-signature`,
          note: "Nothing has been sent. Sending for signature is a separate, explicit action.",
        },
        hardStop: "legal_signing",
      },
      201,
    );
  }
  if (url.includes("/request-signature")) {
    return json({
      signingLinks: [
        {
          signerId: "signer-1",
          name: "Dolores Whitfield",
          email: "dolores@example.com",
          role: "seller",
          url: "https://app.example.com/sign/abc",
        },
      ],
    });
  }
  return json([]);
}

function wrap(node: React.ReactNode) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } });
  return React.createElement(
    QueryClientProvider,
    { client },
    React.createElement(Router, null, node),
  );
}

async function flush() {
  await act(async () => {
    await new Promise((r) => setTimeout(r, 0));
    await new Promise((r) => setTimeout(r, 0));
    await new Promise((r) => setTimeout(r, 0));
  });
}

let container: HTMLDivElement;
let root: Root;

beforeEach(() => {
  calls = [];
  state.previewRefusesWithWyoming = false;
  vi.stubGlobal(
    "fetch",
    vi.fn((input: RequestInfo | URL, init?: RequestInit) => fetchMock(String(input), init)),
  );
  container = document.createElement("div");
  document.body.appendChild(container);
  root = createRoot(container);
});

afterEach(async () => {
  await act(async () => root.unmount());
  container.remove();
  vi.unstubAllGlobals();
});

async function mount() {
  await act(async () => {
    root.render(
      wrap(
        React.createElement(ContractChainSection, {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          deals: [deal] as never,
          dealsLoading: false,
          dealsError: null,
          onRetryDeals: () => {},
          properties: [property] as never,
        }),
      ),
    );
  });
  await flush();
}

/** The review step renders in a Radix portal, so query the whole document. */
function q(selector: string): HTMLElement | null {
  return document.body.querySelector<HTMLElement>(selector);
}

async function click(selector: string) {
  const el = q(selector);
  if (!el) throw new Error(`missing element: ${selector}`);
  await act(async () => {
    el.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
  });
  await flush();
}

const writes = () => calls.filter((c) => c.method !== "GET");

describe("contract chain — nothing happens without an operator", () => {
  it("mounting the surface issues no writes and no sends", async () => {
    await mount();
    expect(q(`[data-testid="card-contract-deal-${DEAL_ID}"]`)).not.toBeNull();
    expect(q(`[data-testid="button-prepare-contract-${DEAL_ID}"]`)).not.toBeNull();
    expect(writes()).toHaveLength(0);
    expect(calls.some((c) => c.url.includes("/contract-preview"))).toBe(false);
  });

  it("opening the review step is a READ — it creates nothing and sends nothing", async () => {
    await mount();
    await click(`[data-testid="button-prepare-contract-${DEAL_ID}"]`);

    // The exact body that would go out is on screen…
    const shown = q('[data-testid="contract-preview-content"]');
    expect(shown).not.toBeNull();
    expect(shown?.textContent).toContain("REAL ESTATE PURCHASE AGREEMENT");
    expect(shown?.textContent).toContain("Dolores Whitfield");
    expect(shown?.textContent).toContain("Peachtree Holdings LLC");
    expect(shown?.textContent).toContain("$182,500.00");

    // …and the review is explicitly not a send.
    expect(calls.filter((c) => c.url.includes("/contract-preview"))).toHaveLength(1);
    expect(writes()).toHaveLength(0);
    expect(document.body.textContent).toContain("Nothing sent yet");
    expect(document.body.textContent).toContain("founder-only hard-stop");
  });

  it("the draft cannot be created until the operator confirms THIS content", async () => {
    await mount();
    await click(`[data-testid="button-prepare-contract-${DEAL_ID}"]`);

    const create = q('[data-testid="button-create-contract"]') as HTMLButtonElement | null;
    expect(create).not.toBeNull();
    expect(create?.disabled).toBe(true);

    // Clicking the disabled action changes nothing.
    await click('[data-testid="button-create-contract"]');
    expect(writes()).toHaveLength(0);

    await click('[data-testid="checkbox-confirm-review"]');
    expect(
      (q('[data-testid="button-create-contract"]') as HTMLButtonElement | null)?.disabled,
    ).toBe(false);

    await click('[data-testid="button-create-contract"]');

    const created = calls.filter((c) => c.url === `/api/deals/${DEAL_ID}/contract`);
    expect(created).toHaveLength(1);
    expect(created[0].method).toBe("POST");
    expect(created[0].body).toMatchObject({
      kind: "purchase_agreement",
      confirmReviewed: true,
      // The seal is the sha256 of the body the operator was actually shown.
      reviewedContentHash: draft.contentHash,
    });

    // Creating a draft is NOT sending it.
    expect(calls.some((c) => c.url.includes("/request-signature"))).toBe(false);
    expect(document.body.textContent).toContain("has not been sent");
  });

  it("the signing rail is reached only by a further, separate click", async () => {
    await mount();
    await click(`[data-testid="button-prepare-contract-${DEAL_ID}"]`);
    await click('[data-testid="checkbox-confirm-review"]');
    await click('[data-testid="button-create-contract"]');
    expect(calls.some((c) => c.url.includes("/request-signature"))).toBe(false);

    await click('[data-testid="button-send-for-signature"]');
    const sends = calls.filter((c) => c.url.includes("/request-signature"));
    expect(sends).toHaveLength(1);
    expect(sends[0].url).toBe(`/api/generated-documents/${DOCUMENT_ID}/request-signature`);
    // AcreOS mints links; the operator delivers them.
    expect(document.body.textContent).toContain("copy each into your own email");
  });
});

describe("contract chain — an unconfigured state refuses by name", () => {
  it("names the state, quotes the server's refusal, and offers no document", async () => {
    state.previewRefusesWithWyoming = true;
    await mount();
    await click(`[data-testid="button-prepare-contract-${DEAL_ID}"]`);

    const refusal = q('[data-testid="contract-refusal"]');
    expect(refusal).not.toBeNull();
    // The state is named — both its code and its full name.
    expect(refusal?.textContent).toContain("Wyoming");
    expect(refusal?.textContent).toContain("WY");
    // …in the server's own words, verbatim.
    expect(q('[data-testid="contract-refusal-message"]')?.textContent).toBe(WY_REFUSAL.message);
    expect(WY_REFUSAL.message).toContain("Wyoming");

    // No document, no fallback, no way forward from here.
    expect(q('[data-testid="contract-preview-content"]')).toBeNull();
    expect(q('[data-testid="button-create-contract"]')).toBeNull();
    expect(q('[data-testid="checkbox-confirm-review"]')).toBeNull();
    expect(writes()).toHaveLength(0);
  });
});
