/**
 * Sitemap content-registry coverage.
 *
 * The committed client/public/sitemap.xml is regenerated by
 * script/generate-sitemap.ts. Before this guard, the generator built ONLY from
 * shared/seo/public-routes.ts (static marketing routes, zero /learn), so the
 * next build silently stripped every statute-grade /learn page, the county
 * pages, and the free tools out of the sitemap.
 *
 * These tests assert the generator's URL set stays in lockstep with the content
 * registries, so a regression that drops them fails CI instead of failing
 * Google.
 */

import { describe, it, expect } from "vitest";
import {
  listLearnContentRoutes,
  listCountyContentRoutes,
} from "../../shared/seo/content-routes.js";
import { PUBLIC_ROUTES } from "../../shared/seo/public-routes.js";
import { collectSitemapEntries } from "../../script/generate-sitemap.js";

const ISO_DAY = /^\d{4}-\d{2}-\d{2}$/;

describe("sitemap content-route enumeration", () => {
  const entries = collectSitemapEntries();
  const paths = entries.map((e) => e.path);
  const learnEntries = entries.filter(
    (e) => e.path.startsWith("/learn/") && !e.path.startsWith("/learn/county/"),
  );
  const countyEntries = entries.filter((e) =>
    e.path.startsWith("/learn/county/"),
  );

  it("emits one sitemap URL per /learn content file (no silent drops)", () => {
    const registry = listLearnContentRoutes();
    expect(registry.length).toBeGreaterThan(0);
    expect(learnEntries.length).toBe(registry.length);
  });

  it("emits one sitemap URL per county content file", () => {
    const registry = listCountyContentRoutes();
    expect(registry.length).toBeGreaterThan(0);
    expect(countyEntries.length).toBe(registry.length);
  });

  it("includes the known statute-grade /learn pages", () => {
    // These are our highest-value, hand-authored pages — if any vanish from
    // the sitemap, this assertion catches it.
    for (const p of [
      "/learn/land-flipping/texas",
      "/learn/land-flipping/florida",
      "/learn/land-flipping/arizona",
      "/learn/note-investing/texas",
    ]) {
      expect(paths).toContain(p);
    }
  });

  it("includes the county pages (cochise / navajo / brewster)", () => {
    for (const p of [
      "/learn/county/arizona/cochise",
      "/learn/county/arizona/navajo",
      "/learn/county/texas/brewster",
    ]) {
      expect(paths).toContain(p);
    }
  });

  it("includes the free public tools", () => {
    expect(paths).toContain("/tools/parcel-check");
    expect(paths).toContain("/tools/calculator");
    // ...and they live in PUBLIC_ROUTES so robots.txt allows them too.
    const publicPaths = PUBLIC_ROUTES.map((r) => r.path);
    expect(publicPaths).toContain("/tools/parcel-check");
    expect(publicPaths).toContain("/tools/calculator");
  });

  it("derives per-URL lastmod (not a single blanket today-stamp)", () => {
    for (const e of entries) {
      expect(e.lastmod).toMatch(ISO_DAY);
    }
    // Content pages should not all share one date — that's the smell Google
    // discounts. With real content (figures asOf 06-06, git mtimes, county
    // generatedAt 06-07) the learn+county set spans more than one day.
    const contentDays = new Set(
      [...learnEntries, ...countyEntries].map((e) => e.lastmod),
    );
    expect(contentDays.size).toBeGreaterThan(1);
  });

  it("contains no duplicate URLs", () => {
    expect(new Set(paths).size).toBe(paths.length);
  });
});
